name: streamlit_app
channels:
  - conda-forge
dependencies:
  - matplotlib=3.7.1
  - numpy=1.24.2
  - pip=23.0.1
  - python=3.10.10
  - streamlit=0.62.0
  - scikit-learn==0.22.2.post1
  - pandas=
  - pycarrot= 

